### ISSUE TITLE
Unicode characters found in source code

### ISSUE THREAD

**Issue by kakyoism** [kiyolee/libiconv-win-build#1]
Thanks for this build. It helped me a lot.
I'd like to point out one issue though: I found a lot of non-ASCII "single-quote" characters in libiconv-win-build\include\iconv.h file, which gives me a lot of [C4819 warnings](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=vs-2019) . 

It'd be great if those could be fixed with the ASCII versions.

**Comment by kiyolee** [comment]
See the annoyance. Those non-ASCII single quotes are now replaced.
