### ISSUE TITLE
Some Gnulib licenses are incorrect

### ISSUE THREAD

**Issue by HertzDevil** [kiyolee/libiconv-win-build#2]
The following files from [Gnulib](https://www.gnu.org/software/gnulib/) are licensed under GPL here, but are really under LGPL:

* `srclib/binary-io.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/binary-io.h;h=642f08b1ba38c295de63d2bdc42cb7a5e74e5ab4;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/binary-io;h=549be1721b96910b2c6c3861071bea7de4b1a252;hb=HEAD))
* `srclib/gettext.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/gettext.h;h=01d9c1cf6bc53f3b6b51cba17a23bbf3ad46bbce;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/gettext-h;h=a0036d09c4c2858946cb2e5403004369e427301c;hb=HEAD))
* `srclib/localcharset.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/localcharset.h;h=0ff49544bb7d80b0cd11b7b74423a0f789fec057;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/localcharset;h=65ab529e95bf6ba2383c1b33fe4655073affe29f;hb=HEAD))
* `srclib/safe-read.c` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/safe-read.c;h=e187b12586ba5b2f2848d6286d000a8cb8a8cc61;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/safe-read;h=f19e14b8c7bcb96d004b266c4fb7a01085f098b0;hb=HEAD))
* `srclib/safe-read.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/safe-read.h;h=111aff5c4fc1d0193f3a534c7fefd09dba242cea;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/safe-read;h=f19e14b8c7bcb96d004b266c4fb7a01085f098b0;hb=HEAD))
* `srclib/streq.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/streq.h;h=adabd158e17b5445b7733fe2bb45717c276df4fd;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/streq;h=de509ccb29be5af8126ededea3485d517bffaf40;hb=HEAD))
* `srclib/sys-limits.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/sys-limits.h;h=2d9784d1b65a3533726dc4ce42ff5d09559fdfbb;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/safe-read;h=f19e14b8c7bcb96d004b266c4fb7a01085f098b0;hb=HEAD))
* `srclib/unitypes.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/unitypes.in.h;h=82ee0de88bca0b552df6abde930de6db5e00a3d9;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/unitypes;h=46ed80d8c83cfae0d099e0380b96cacd0df31117;hb=HEAD))
* `srclib/uniwidth.h` ([source](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/uniwidth.in.h;h=0859254efc3853eece01dc1e6b9c371a56e4850d;hb=HEAD), [module](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=modules/uniwidth/base;h=fbf4d41f5013fea4c952295ff3b8c9ff4c875bad;hb=HEAD))

The most important one is `localcharset.h` because it is also referenced by the libiconv project files; libiconv is LGPL, so `localcharset.h` cannot be GPL. (The original repository seems to use [`libcharset/include/localcharset.h`](https://git.savannah.gnu.org/gitweb/?p=libiconv.git;a=blob;f=libcharset/include/localcharset.h.in;h=34ce0adde9bb793f1c1cd5f81b5cc3d2eff08ab1;hb=HEAD) instead, and that local copy is LGPL already.)

For libiconv to be completely LGPL, it also cannot reference `srclib/xalloc.h`, however that file plus `unitypes.h` and `uniwidth.h` seem unused by libiconv already.

**Comment by kiyolee** [comment]
I made minimal changes to some of these files and I thought they just follow whatever licence they originally carry.
All these source files you mentioned come from the same official source tarball, I would suppose the licence allows the source files to be used together.
There is no binary deliverable here anyway so I don't think I have violated GPL or LGPL.
It is whoever needs to ship binaries produced out of the source (either this repo or original tarball) that they may need to follow the requirement and/or limitations of LGPL.
Please advise if I have missed or misunderstood anything.
However, I have now added a LICENSE.md to clarify the licence for original files I have added.
