### ISSUE TITLE
expect feature: set postfix of output name for every configuration

### ISSUE THREAD

**Issue by walkthetalk** [kiyolee/libiconv-win-build#3]

**Comment by kiyolee** [comment]
No idea what exactly you mean.
But I do specifically have the same dll/lib name so other projects referring to this repo can simply use the same name everywhere.
Postfix/subfix just make thing messy.
In a way, the subdirectory for the dll/lib are effectively already the postfix.
There are pros and cons for both approaches.
I prefer my way which works better for what I want.
