### ISSUE TITLE
VSCode 2022 doesn't build out of the box

### ISSUE THREAD

**Issue by sneurlax** [kiyolee/libiconv-win-build#5]
Hi!  Thanks for your project.  VSCode 2022 doesn't help configure builds any more.  I had to downgrade to VSCode 2019 in order to build: VSCode 2022 needs tasks to be configured manually and none of the built-in templates help.  Although you may have no issues building on whatever old version of VSC you're using, you may consider providing more guidance on building through later VSCode versions or the commandline.

**Comment by kiyolee** [comment]
VSCode? The repo here is mainly for Visual Studio. There is nothing here specifically relating to VSCode.
Can you clarify your question?
