### ISSUE TITLE
Build Steps

### ISSUE THREAD

**Issue by sanjampreet00** [kiyolee/libiconv-win-build#6]
Hi Kiyolee, I wanted your help to build libiconv on my system from scratch can you please help me for the same. I am not able to build the VS file itself, it will be very helpful if you share the steps.

**Comment by kiyolee** [comment]
First of all, are you talking about Windows? If not, there is nothing I would help through here.
If indeed for Windows, what error do you get if when building using one of VS solutions here with what version of VS?

**Comment by sanjampreet00** [comment]
Yes, I am trying to build it in windows. So I need to build the VS solution for it which I don't know how to build it will be very helpful if you provide the steps how you build the VS-2017 MT sln file

**Comment by kiyolee** [comment]
My set of sln files are manually created, the process was a bit tedious and manual. You need to read through various instructions and make files, a fair amount of testing as well. That's why I share those so nobody needs to recreate them. The sln files are meant to used directly. I don't understand why you need to recreate you own.

**Comment by sanjampreet00** [comment]
So, I need to create the files as it is directly consumed from our automation. So I haven't migrated from a long time and now not able to build the latest with the previous codeset. If you can provide the set of instructions how to build I can try to repro it and create an automation for the same.

**Comment by kiyolee** [comment]
I don't think I can help for your purpose then. Why can't you just clone this repo and call msbuild to build things automatically? The alternative solution may be just use vcpkg which is more designed for automation.
