### ISSUE TITLE
Crashes due to illegal instruction (AVX)

### ISSUE THREAD

**Issue by triplef** [kiyolee/libiconv-win-build#7]
Using the latest commits enabling AVX we’re seeing crashes on various machines in `libiconv_open()` due to `EXCEPTION_ILLEGAL_INSTRUCTION` at a memory location containing the `vmovups` AVX instruction.

I don’t yet have information about the processors on affected machines, but presumably they don’t support AVX. It would be great if support for such CPUs could be maintained.

**Comment by kiyolee** [comment]
You must be using very old CPU before Haswell (10 years old) for AVX2 or Sandy Bridge (12 years old) for AVX.
I was assuming Haswell (or Sandy Bridge for VS2010) as minimum requirement was reasonable.
Unfortunately, I have recently applied that assumption across all my github offerings.
Which version of VS and what CPU are you using?
If you are using something between Sandy Bridge and before Haswell, you may try VS2010 build.
If you do need older CPU support, you may fork the repo and reverts that AVX change.

**Comment by kiyolee** [comment]
Just notice you are from gnustep which is a project I admire.
Would that help if I maintain a separate branch that builds without AVX?
I am happy to maintain that branch for your project.

**Comment by triplef** [comment]
Thanks for your feedback and glad to hear you appreciate GNUstep. 🙂 

I found out one of the affected machines has this Intel Celeron CPU from 2019, and if I read it correctly it doesn't have AVX:
https://www.intel.com/content/www/us/en/products/sku/197310/intel-celeron-processor-n4020-4m-cache-up-to-2-80-ghz.html

This is in an entry level Lenovo laptop but it runs Windows 10 just fine.

**Comment by kiyolee** [comment]
Interesting. I have completely overlooked lower end Intel CPU which does not have AVX.
Perhaps I should just revert the AVX changes.
AVX is probably not helping much for libiconv.

**Comment by kiyolee** [comment]
I have reverted the AVX changes.
Hope nobody complains they now want AVX.

**Comment by triplef** [comment]
Thank you! I appreciate you maintaining this.
