### ISSUE TITLE
If possible, make the binaries available for Windows along with a newer version of iconv

### ISSUE THREAD

**Issue by insinfo** [kiyolee/libiconv-win-build#8]
If possible, make the binaries available for Windows along with a newer version of iconv

**Comment by kiyolee** [comment]
I am sorry I cannot do this.
However, I believe the current version is already the latest. This library updates very infrequently.

**Comment by JustMyGithub** [comment]
Hi @kiyolee,
would you mind explaining why you *cannot* provide the binaries along with the vs project files?
I do not see a obvious reason besides that you may not want to. What do I oversee?

thanks!
